[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mysqli', 'php82Extensions.mbstring', 'php82Extensions.gd', 'php82Extensions.zip', 'php82Extensions.curl', 'php82Extensions.openssl']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'
